
- name: reload systemd configuration
  become: yes
  systemd:
    daemon_reload: true

# Restart service and ensure it is enabled
- name: restart kibana
  become: yes
  service: name=kibana state=restarted enabled=yes
  register: kibana_restarted
