# ----------------------------------------------------------------------------
# Restart Kibana
# ----------------------------------------------------------------------------
---

- name: Restart kibana
  systemd:
      name: 'kibana'
      state: restarted
  become: true