# ----------------------------------------------------------------------------
# Check if kibana is running
# ----------------------------------------------------------------------------
---

- name: Verify kibana is running
  block:
    - name: Get kibana process
      become: yes
      shell: "lsof -i:{{ kibana_port }} | tail -1 | awk '{print $2}'"
      args:
        executable: /bin/bash
      register: kibana_process_id
      until: kibana_process_id.stdout | length > 0
      retries: 30
      delay: 3
      changed_when: false
      
    - name: Fail if kibana process is not running
      fail:
        msg: 'kibana is not running'
      when: kibana_process_id.stdout | length == 0